### PR TITLE
update configure script by autoreconf -vfi

### PR DESCRIPTION
**Pull request by skaji**
As described in https://github.com/rakudo/rakudo/issues/4317,
I failed to build rakudo on M1 Mac with the following error:

```
checking build system type... Invalid configuration `arm64-apple-darwin20.3.0': machine `arm64-apple' not recognized
configure: error: /bin/sh ./config.sub arm64-apple-darwin20.3.0 failed
make: *** [3rdparty/libatomicops/src/libatomic_ops.a] Error 1
```

This PR updates `configure` script by `autoreconf -vfi`.
I have confirmed that I was able to build rakudo on M1 Mac with this change.

### CODE REVIEW

**Comment by lizmat** [comment]
OK to merge after the 2021.4 release.

**Comment by skaji** [comment]
@lizmat Is it time to merge this PR?

**Comment by lizmat** [comment]
I think so.  Sadly I do not have rights to do so.

**Comment by skaji** [comment]
@lizmat I see, thanks 😢

**Comment by MasterDuke17** [comment]
Upstream (https://github.com/ivmai/libatomic_ops) is at 7.6.10. I don't see any mention of M1 Macs in their changelog, but would it make sense to PR this change upstream also/instead?

**Comment by skaji** [comment]
@MasterDuke17 Thanks for your comment.

Upstream (https://github.com/ivmai/libatomic_ops) does not commit `configure` script into their git repository.
Thus, I don't think it needs this change per se.

**Comment by nwc10** [comment]
On the M1 Mac Mini I have access to (part of the GCC compiler farm) I could build MoarVM without this change. On this machine `uname -p` reports `arm`. I infer that on your machine, it reports `arm64` (and I have no idea why they differ)

Somewhere deep in `config.guess` I spot this diff:

```
        exit ;;
     *:Rhapsody:*:*)
-       echo ${UNAME_MACHINE}-apple-rhapsody${UNAME_RELEASE}
+       echo "$UNAME_MACHINE"-apple-rhapsody"$UNAME_RELEASE"
+       exit ;;
+    arm64:Darwin:*:*)
+       echo aarch64-apple-darwin"$UNAME_RELEASE"
        exit ;;
     *:Darwin:*:*)
```

I figure that that is what fixes the problem.

Merged. Thanks for the fix.

**Comment by skaji** [comment]
@nwc10 Wow, you're absolutely right!

I checked my environment carefully, then it turned out that
the reason why `uname -p` returns `arm64` on my environment is that, I put `/opt/homebrew/opt/coreutils/libexec/gnubin` in `$PATH` and `uname` is actually `/opt/homebrew/opt/coreutils/libexec/gnubin/uname`.
```
❯ uname -p
arm64

❯ which -a uname
/opt/homebrew/opt/coreutils/libexec/gnubin/uname
/usr/bin/uname

❯ /opt/homebrew/opt/coreutils/libexec/gnubin/uname -p
arm64

❯ /usr/bin/uname -p
arm
``` 

Sorry, I should have realized that earlier.

**Comment by nwc10** [comment]
Turns out that I can replicate this:

```
nick@minimac ~ % /opt/homebrew/opt/coreutils/libexec/gnubin/uname -p
arm64
nick@minimac ~ % /usr/bin/uname -p
arm
```

> Sorry, I should have realized that earlier.

There's no need to apologise. I had no idea that there was this trap, and it's good that we found why your setup is not the same as the machine I have access to. If we don't fix the trap, someone else is going to fall into it, and maybe they will quietly give up, instead of being like you and trying to figure out a fix.

Also I'm hoping that regenerating all the somewhat outdated `autoconf` files brings in other bug fixes (and doesn't introduce regressions), meaning that we might have fixed other problems before anyone else finds them.

**Pull request merged**
